/*
 * skeleton for the tests generated by memtestgen.  This file is included by the
 * generated source file of each test case.  The generated files only contain
 * the definition of struct testcase, the functions prototyped below and the
 * constant TESTFSTR.  This file contains the code that calls the memf()
 * functions and validates them on the generated structure and test cases.
 */

#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include "memf.h"

/* defined by the includer */
struct testcase;

static size_t 	testsize(void); /* returns sizeof (struct testcase) */
static size_t 	testlen(void);  /* should be equal to lenf(TESTFSTR) */
static void 	filltest(struct testcase*); /* fill testcase with testing pattern */
static void	cleartest(struct testcase*); /* set each member to 0 */
static int	iscorrect(const struct testcase*); /* check against testing pattern */

/* auxillary functions */
static void pass(const char*, ...);
static void fail(const char*, ...);

/* each test has this format */
typedef void testcase(void);

static testcase test1, test2;

/* test 1: Is testlen() == lenf()? */
static int
test1(void)
{
	size_t tl_expect, tl_is;

	tl_expect = testlen();
	tl_is = lenf(TESTFSTR);

	if (tl_expect == tl_is)
		pass("%d == %d", tl_expect, tl_is);
	else
		fail("%d != %d", tl_expect, tl_is);
}

/* test 2: Is testsize() >= sizef()? */
static int
test1(void)
{
	size_t ts_expect, ts_is;

	ts_expect = testsize();
	ts_is = sizef(TESTFSTR);

	if (ts_expect >= ts_is)
		pass("%d >= %d", ts_expect, ts_is);
	else
		fail("%d <  %d", ts_expect, ts_is);
}


